// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4lFB-Xi_dQ9KitJIueb92EaOzwrYHwVM',
    appId: '1:414025773323:web:fbfa6612c4794e1687f20e',
    messagingSenderId: '414025773323',
    projectId: 'we-easy-4da55',
    authDomain: 'we-easy-4da55.firebaseapp.com',
    storageBucket: 'we-easy-4da55.appspot.com',
    measurementId: 'G-DZHJNRZZ56',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBp4fbHYaGKjWJxC9XBrCliYOnhGxkiEsE',
    appId: '1:414025773323:android:9d73f897d51a719287f20e',
    messagingSenderId: '414025773323',
    projectId: 'we-easy-4da55',
    storageBucket: 'we-easy-4da55.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtSIYrvTnWCCaAxe0GyJAi53RtqDCTlNw',
    appId: '1:414025773323:ios:efad92818be15d1587f20e',
    messagingSenderId: '414025773323',
    projectId: 'we-easy-4da55',
    storageBucket: 'we-easy-4da55.appspot.com',
    iosBundleId: 'com.example.weEasy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtSIYrvTnWCCaAxe0GyJAi53RtqDCTlNw',
    appId: '1:414025773323:ios:638017408b0aa36187f20e',
    messagingSenderId: '414025773323',
    projectId: 'we-easy-4da55',
    storageBucket: 'we-easy-4da55.appspot.com',
    iosBundleId: 'com.example.weEasy.RunnerTests',
  );
}
